bind 0.0.0.0
port 6379
workers 2
timeout 0
tcp-backlog 512
daemonize no
dir /data
db-name db
log-dir stdout
redis-cursor-compatible no
max-io-mb 100
rocksdb.compression snappy
rocksdb.block_cache_size 128
rocksdb.metadata_block_cache_size 128
rocksdb.subkey_block_cache_size 128
rocksdb.write_buffer_size 32
rocksdb.max_background_compactions 1
rocksdb.max_background_flushes 1
rocksdb.max_background_jobs 2
